"""hr employee document

Revision ID: f7a1c2d3e4b5
Revises: e5f7a9b1c3d4
Create Date: 2026-09-10

Adds hr.employee_document — employee document storage (stage 1.1). The row is
the only index of a file held in object storage under object_key.

Hand-written rather than autogenerated: autogenerate on this repo also surfaces
pre-existing cap.* drift that would have to be stripped out by hand anyway.
"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7a1c2d3e4b5"
down_revision = "e5f7a9b1c3d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "employee_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CONTRACT",
                "IDENTIFICATION",
                "CERTIFICATION",
                "LICENCE",
                "QUALIFICATION",
                "MEDICAL",
                "DISCIPLINARY",
                "APPRAISAL",
                "SIGNED_FORM",
                "OTHER",
                name="documentcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "sensitivity",
            sa.Enum("STANDARD", "RESTRICTED", name="documentsensitivity"),
            nullable=False,
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(length=2000),
            nullable=True,
        ),
        sa.Column(
            "object_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "issuing_authority",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "reference_number",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=True,
        ),
        sa.Column(
            "entity_type", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("archived_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("employee_document_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["user.id"],
            name=op.f("employee_document_uploaded_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["archived_by_user_id"],
            ["user.id"],
            name=op.f("employee_document_archived_by_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("employee_document_pkey")),
        schema="hr",
    )
    op.create_index(
        op.f("hr_employee_document_user_id_idx"),
        "employee_document",
        ["user_id"],
        unique=False,
        schema="hr",
    )
    op.create_index(
        op.f("hr_employee_document_object_key_idx"),
        "employee_document",
        ["object_key"],
        unique=True,
        schema="hr",
    )
    op.create_index(
        "ix_hr_employee_document_user_id_category",
        "employee_document",
        ["user_id", "category"],
        unique=False,
        schema="hr",
    )
    # The stage 1.2 expiry sweep scans this column across all users.
    op.create_index(
        "ix_hr_employee_document_expiry_date",
        "employee_document",
        ["expiry_date"],
        unique=False,
        schema="hr",
    )
    op.create_index(
        "ix_hr_employee_document_entity",
        "employee_document",
        ["entity_type", "entity_id"],
        unique=False,
        schema="hr",
    )


def downgrade() -> None:
    op.drop_index(
        "ix_hr_employee_document_entity", table_name="employee_document", schema="hr"
    )
    op.drop_index(
        "ix_hr_employee_document_expiry_date",
        table_name="employee_document",
        schema="hr",
    )
    op.drop_index(
        "ix_hr_employee_document_user_id_category",
        table_name="employee_document",
        schema="hr",
    )
    op.drop_index(
        op.f("hr_employee_document_object_key_idx"),
        table_name="employee_document",
        schema="hr",
    )
    op.drop_index(
        op.f("hr_employee_document_user_id_idx"),
        table_name="employee_document",
        schema="hr",
    )
    op.drop_table("employee_document", schema="hr")
    op.execute("DROP TYPE IF EXISTS documentsensitivity")
    op.execute("DROP TYPE IF EXISTS documentcategory")
