"""baseline schema

Revision ID: b5a1503a7136
Revises: 
Create Date: 2026-03-06 01:29:01.513047

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5a1503a7136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS hr")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_department_name'), 'department', ['name'], unique=True, schema='hr')
    op.create_table('shift_catalog',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('category', sa.Enum('WORK', 'OFF', 'LEAVE', 'HOLIDAY', name='shiftcategory'), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('counts_as_work_hours', sa.Boolean(), nullable=False),
    sa.Column('needs_reason', sa.Boolean(), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='hr'
    )
    op.create_table('permission',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('access', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_key'), 'permission', ['key'], unique=True)
    op.create_table('role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('approval_authority',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('can_approve_leave', sa.Boolean(), nullable=False),
    sa.Column('can_approve_shift_swap', sa.Boolean(), nullable=False),
    sa.Column('can_approve_timesheets', sa.Boolean(), nullable=False),
    sa.Column('can_approve_absentee_reports', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_approval_authority_user_id'), 'approval_authority', ['user_id'], unique=True, schema='hr')
    op.create_table('department_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allow_employee_self_submit', sa.Boolean(), nullable=False),
    sa.Column('allow_supervisor_proxy_submit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_department_policy_department_id'), 'department_policy', ['department_id'], unique=True, schema='hr')
    op.create_table('employment_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', name='employmenttype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('work_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'TERMINATED', name='employmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index('ix_hr_employment_record_department_id', 'employment_record', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_employment_record_employee_number'), 'employment_record', ['employee_number'], unique=True, schema='hr')
    op.create_index('ix_hr_employment_record_status', 'employment_record', ['status'], unique=False, schema='hr')
    op.create_index('ix_hr_employment_record_supervisor_id', 'employment_record', ['supervisor_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_employment_record_user_id'), 'employment_record', ['user_id'], unique=True, schema='hr')
    op.create_table('leave_balance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type', name='uq_hr_leave_balance_user_type'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_balance_user_id'), 'leave_balance', ['user_id'], unique=False, schema='hr')
    op.create_table('leave_carry_over',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type', name='uq_hr_leave_carry_over_user_type'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_carry_over_user_id'), 'leave_carry_over', ['user_id'], unique=False, schema='hr')
    op.create_table('public_holiday',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_public_holiday_holiday_date'), 'public_holiday', ['holiday_date'], unique=False, schema='hr')
    op.create_table('roster_period',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='rosterperiodstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_period_created_by_user_id'), 'roster_period', ['created_by_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_roster_period_department_id'), 'roster_period', ['department_id'], unique=False, schema='hr')
    op.create_table('roster_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_shift_pattern', sa.Enum('ROTATION', 'FIXED', 'FLEX', name='shiftpattern'), nullable=False),
    sa.Column('max_night_shifts_per_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_preference_user_id'), 'roster_preference', ['user_id'], unique=True, schema='hr')
    op.create_table('roster_preferred_shift',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shift_code', name='uq_hr_roster_preferred_shift_user_id_shift_code'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_preferred_shift_user_id'), 'roster_preferred_shift', ['user_id'], unique=False, schema='hr')
    op.create_table('roster_restricted_shift',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shift_code', name='uq_hr_roster_restricted_shift_user_id_shift_code'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_restricted_shift_user_id'), 'roster_restricted_shift', ['user_id'], unique=False, schema='hr')
    op.create_table('timesheet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timesheetstatus'), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_timesheet_department_id'), 'timesheet', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_timesheet_user_id'), 'timesheet', ['user_id'], unique=False, schema='hr')
    op.create_table('user_address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('line_1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('line_2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('parish', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_user_address_user_id'), 'user_address', ['user_id'], unique=True, schema='hr')
    op.create_table('user_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_user_profile_user_id'), 'user_profile', ['user_id'], unique=True, schema='hr')
    op.create_table('workflow_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_type', sa.Enum('LEAVE_REQUEST', 'SHIFT_SWAP', 'ABSENTEE_REPORT', 'STATUS_REPORT', 'TIMESHEET', name='workflowtype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_workflow_template_department_id'), 'workflow_template', ['department_id'], unique=False, schema='hr')
    op.create_table('role_permission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('session',
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_role_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('SELF', 'DEPARTMENT', 'ALL', name='roleassignmentscope'), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_assignment_role_id'), 'user_role_assignment', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignment_user_id'), 'user_role_assignment', ['user_id'], unique=False)
    op.create_table('userimage',
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('roster_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roster_period_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roster_period_id'], ['hr.roster_period.id'], ),
    sa.ForeignKeyConstraint(['shift_code'], ['hr.shift_catalog.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assignment_date', name='uq_hr_roster_assignment_user_date'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_assignment_assignment_date'), 'roster_assignment', ['assignment_date'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_roster_assignment_roster_period_id'), 'roster_assignment', ['roster_period_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_roster_assignment_user_id'), 'roster_assignment', ['user_id'], unique=False, schema='hr')
    op.create_table('roster_import_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('roster_period_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATED', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('error_summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['roster_period_id'], ['hr.roster_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_import_job_created_by_user_id'), 'roster_import_job', ['created_by_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_roster_import_job_department_id'), 'roster_import_job', ['department_id'], unique=False, schema='hr')
    op.create_table('roster_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roster_period_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'ASSIGNMENTS_UPDATED', 'PUBLISHED', 'CLOSED', name='rosterrevisionaction'), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['roster_period_id'], ['hr.roster_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_revision_roster_period_id'), 'roster_revision', ['roster_period_id'], unique=False, schema='hr')
    op.create_table('timesheet_submission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timesheet_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('submission_mode', sa.Enum('SELF', 'PROXY', name='submissionmode'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['hr.timesheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_timesheet_submission_submitted_by_user_id'), 'timesheet_submission', ['submitted_by_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_timesheet_submission_timesheet_id'), 'timesheet_submission', ['timesheet_id'], unique=False, schema='hr')
    op.create_table('workflow_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_template_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_type', sa.Enum('LEAVE_REQUEST', 'SHIFT_SWAP', 'ABSENTEE_REPORT', 'STATUS_REPORT', 'TIMESHEET', name='workflowtype'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'RETURNED', 'APPROVED', 'REJECTED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['hr.workflow_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_workflow_instance_department_id'), 'workflow_instance', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_instance_entity_id'), 'workflow_instance', ['entity_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_instance_requested_by_user_id'), 'workflow_instance', ['requested_by_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_instance_workflow_template_id'), 'workflow_instance', ['workflow_template_id'], unique=False, schema='hr')
    op.create_table('workflow_step_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_template_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.Uuid(), nullable=False),
    sa.Column('required_scope', sa.Enum('SELF', 'DEPARTMENT', 'ALL', name='roleassignmentscope'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['required_role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['hr.workflow_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_workflow_step_template_required_role_id'), 'workflow_step_template', ['required_role_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_step_template_workflow_template_id'), 'workflow_step_template', ['workflow_template_id'], unique=False, schema='hr')
    op.create_table('absentee_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('expected_shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('absence_start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('absence_end_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('reason_code', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('contact_attempted', sa.Boolean(), nullable=False),
    sa.Column('contact_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('replacement_arranged', sa.Boolean(), nullable=False),
    sa.Column('replacement_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['replacement_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_absentee_report_department_id'), 'absentee_report', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_absentee_report_user_id'), 'absentee_report', ['user_id'], unique=False, schema='hr')
    op.create_table('leave_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('leave_type', sa.Enum('VACATION', 'SICK', 'CASUAL', 'MATERNITY', 'PATERNITY', 'STUDY', 'COMPASSIONATE', 'WITHOUT_PAY', 'OTHER', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_requested', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('days_with_pay', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('days_without_pay', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('leave_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('acting_officer_id', sa.Uuid(), nullable=True),
    sa.Column('head_of_dept_comments', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acting_officer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_request_department_id'), 'leave_request', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_leave_request_user_id'), 'leave_request', ['user_id'], unique=False, schema='hr')
    op.create_table('roster_import_row',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roster_import_job_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roster_import_job_id'], ['hr.roster_import_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_roster_import_row_roster_import_job_id'), 'roster_import_row', ['roster_import_job_id'], unique=False, schema='hr')
    op.create_table('shift_swap_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requesting_user_id', sa.Uuid(), nullable=False),
    sa.Column('counterpart_user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('swap_type', sa.Enum('TEMPORARY', 'PERMANENT', name='swaptype'), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('source_shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('restoration_date', sa.Date(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('counterpart_agreed', sa.Boolean(), nullable=False),
    sa.Column('counterpart_agreed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counterpart_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_shift_swap_request_counterpart_user_id'), 'shift_swap_request', ['counterpart_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_shift_swap_request_department_id'), 'shift_swap_request', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_shift_swap_request_requesting_user_id'), 'shift_swap_request', ['requesting_user_id'], unique=False, schema='hr')
    op.create_table('status_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('weather_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('equipment_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('personnel_summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('runway_status', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('navaids_status', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('communications_status', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('general_remarks', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['hr.department.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_status_report_department_id'), 'status_report', ['department_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_status_report_submitted_by_user_id'), 'status_report', ['submitted_by_user_id'], unique=False, schema='hr')
    op.create_table('timesheet_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timesheet_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('shift_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('roster_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('roster_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('break_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roster_assignment_id'], ['hr.roster_assignment.id'], ),
    sa.ForeignKeyConstraint(['shift_code'], ['hr.shift_catalog.code'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['hr.timesheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_timesheet_entry_timesheet_id'), 'timesheet_entry', ['timesheet_id'], unique=False, schema='hr')
    op.create_table('workflow_step_instance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.Uuid(), nullable=False),
    sa.Column('required_scope', sa.Enum('SELF', 'DEPARTMENT', 'ALL', name='roleassignmentscope'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('approver_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'RETURN', 'CANCEL', name='workflowaction'), nullable=True),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['required_role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_workflow_step_instance_approver_user_id'), 'workflow_step_instance', ['approver_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_step_instance_required_role_id'), 'workflow_step_instance', ['required_role_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_workflow_step_instance_workflow_instance_id'), 'workflow_step_instance', ['workflow_instance_id'], unique=False, schema='hr')
    op.create_table('approval_action_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_step_instance_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'RETURN', 'CANCEL', name='workflowaction'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['hr.workflow_instance.id'], ),
    sa.ForeignKeyConstraint(['workflow_step_instance_id'], ['hr.workflow_step_instance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_approval_action_log_actor_user_id'), 'approval_action_log', ['actor_user_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_approval_action_log_workflow_instance_id'), 'approval_action_log', ['workflow_instance_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_approval_action_log_workflow_step_instance_id'), 'approval_action_log', ['workflow_step_instance_id'], unique=False, schema='hr')
    op.create_table('leave_balance_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('delta_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('balance_after_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('related_leave_request_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_leave_request_id'], ['hr.leave_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_leave_balance_event_user_id'), 'leave_balance_event', ['user_id'], unique=False, schema='hr')
    op.create_table('status_report_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status_report_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('personnel_status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'ON_LEAVE', 'EXCUSED', name='personnelstatus'), nullable=False),
    sa.Column('arrival_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('departure_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['status_report_id'], ['hr.status_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_status_report_entry_status_report_id'), 'status_report_entry', ['status_report_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_status_report_entry_user_id'), 'status_report_entry', ['user_id'], unique=False, schema='hr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_status_report_entry_user_id'), table_name='status_report_entry', schema='hr')
    op.drop_index(op.f('ix_hr_status_report_entry_status_report_id'), table_name='status_report_entry', schema='hr')
    op.drop_table('status_report_entry', schema='hr')
    op.drop_index(op.f('ix_hr_leave_balance_event_user_id'), table_name='leave_balance_event', schema='hr')
    op.drop_table('leave_balance_event', schema='hr')
    op.drop_index(op.f('ix_hr_approval_action_log_workflow_step_instance_id'), table_name='approval_action_log', schema='hr')
    op.drop_index(op.f('ix_hr_approval_action_log_workflow_instance_id'), table_name='approval_action_log', schema='hr')
    op.drop_index(op.f('ix_hr_approval_action_log_actor_user_id'), table_name='approval_action_log', schema='hr')
    op.drop_table('approval_action_log', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_step_instance_workflow_instance_id'), table_name='workflow_step_instance', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_step_instance_required_role_id'), table_name='workflow_step_instance', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_step_instance_approver_user_id'), table_name='workflow_step_instance', schema='hr')
    op.drop_table('workflow_step_instance', schema='hr')
    op.drop_index(op.f('ix_hr_timesheet_entry_timesheet_id'), table_name='timesheet_entry', schema='hr')
    op.drop_table('timesheet_entry', schema='hr')
    op.drop_index(op.f('ix_hr_status_report_submitted_by_user_id'), table_name='status_report', schema='hr')
    op.drop_index(op.f('ix_hr_status_report_department_id'), table_name='status_report', schema='hr')
    op.drop_table('status_report', schema='hr')
    op.drop_index(op.f('ix_hr_shift_swap_request_requesting_user_id'), table_name='shift_swap_request', schema='hr')
    op.drop_index(op.f('ix_hr_shift_swap_request_department_id'), table_name='shift_swap_request', schema='hr')
    op.drop_index(op.f('ix_hr_shift_swap_request_counterpart_user_id'), table_name='shift_swap_request', schema='hr')
    op.drop_table('shift_swap_request', schema='hr')
    op.drop_index(op.f('ix_hr_roster_import_row_roster_import_job_id'), table_name='roster_import_row', schema='hr')
    op.drop_table('roster_import_row', schema='hr')
    op.drop_index(op.f('ix_hr_leave_request_user_id'), table_name='leave_request', schema='hr')
    op.drop_index(op.f('ix_hr_leave_request_department_id'), table_name='leave_request', schema='hr')
    op.drop_table('leave_request', schema='hr')
    op.drop_index(op.f('ix_hr_absentee_report_user_id'), table_name='absentee_report', schema='hr')
    op.drop_index(op.f('ix_hr_absentee_report_department_id'), table_name='absentee_report', schema='hr')
    op.drop_table('absentee_report', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_step_template_workflow_template_id'), table_name='workflow_step_template', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_step_template_required_role_id'), table_name='workflow_step_template', schema='hr')
    op.drop_table('workflow_step_template', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_instance_workflow_template_id'), table_name='workflow_instance', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_instance_requested_by_user_id'), table_name='workflow_instance', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_instance_entity_id'), table_name='workflow_instance', schema='hr')
    op.drop_index(op.f('ix_hr_workflow_instance_department_id'), table_name='workflow_instance', schema='hr')
    op.drop_table('workflow_instance', schema='hr')
    op.drop_index(op.f('ix_hr_timesheet_submission_timesheet_id'), table_name='timesheet_submission', schema='hr')
    op.drop_index(op.f('ix_hr_timesheet_submission_submitted_by_user_id'), table_name='timesheet_submission', schema='hr')
    op.drop_table('timesheet_submission', schema='hr')
    op.drop_index(op.f('ix_hr_roster_revision_roster_period_id'), table_name='roster_revision', schema='hr')
    op.drop_table('roster_revision', schema='hr')
    op.drop_index(op.f('ix_hr_roster_import_job_department_id'), table_name='roster_import_job', schema='hr')
    op.drop_index(op.f('ix_hr_roster_import_job_created_by_user_id'), table_name='roster_import_job', schema='hr')
    op.drop_table('roster_import_job', schema='hr')
    op.drop_index(op.f('ix_hr_roster_assignment_user_id'), table_name='roster_assignment', schema='hr')
    op.drop_index(op.f('ix_hr_roster_assignment_roster_period_id'), table_name='roster_assignment', schema='hr')
    op.drop_index(op.f('ix_hr_roster_assignment_assignment_date'), table_name='roster_assignment', schema='hr')
    op.drop_table('roster_assignment', schema='hr')
    op.drop_table('userimage')
    op.drop_index(op.f('ix_user_role_assignment_user_id'), table_name='user_role_assignment')
    op.drop_index(op.f('ix_user_role_assignment_role_id'), table_name='user_role_assignment')
    op.drop_table('user_role_assignment')
    op.drop_table('user_role')
    op.drop_table('session')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_hr_workflow_template_department_id'), table_name='workflow_template', schema='hr')
    op.drop_table('workflow_template', schema='hr')
    op.drop_index(op.f('ix_hr_user_profile_user_id'), table_name='user_profile', schema='hr')
    op.drop_table('user_profile', schema='hr')
    op.drop_index(op.f('ix_hr_user_address_user_id'), table_name='user_address', schema='hr')
    op.drop_table('user_address', schema='hr')
    op.drop_index(op.f('ix_hr_timesheet_user_id'), table_name='timesheet', schema='hr')
    op.drop_index(op.f('ix_hr_timesheet_department_id'), table_name='timesheet', schema='hr')
    op.drop_table('timesheet', schema='hr')
    op.drop_index(op.f('ix_hr_roster_restricted_shift_user_id'), table_name='roster_restricted_shift', schema='hr')
    op.drop_table('roster_restricted_shift', schema='hr')
    op.drop_index(op.f('ix_hr_roster_preferred_shift_user_id'), table_name='roster_preferred_shift', schema='hr')
    op.drop_table('roster_preferred_shift', schema='hr')
    op.drop_index(op.f('ix_hr_roster_preference_user_id'), table_name='roster_preference', schema='hr')
    op.drop_table('roster_preference', schema='hr')
    op.drop_index(op.f('ix_hr_roster_period_department_id'), table_name='roster_period', schema='hr')
    op.drop_index(op.f('ix_hr_roster_period_created_by_user_id'), table_name='roster_period', schema='hr')
    op.drop_table('roster_period', schema='hr')
    op.drop_index(op.f('ix_hr_public_holiday_holiday_date'), table_name='public_holiday', schema='hr')
    op.drop_table('public_holiday', schema='hr')
    op.drop_index(op.f('ix_hr_leave_carry_over_user_id'), table_name='leave_carry_over', schema='hr')
    op.drop_table('leave_carry_over', schema='hr')
    op.drop_index(op.f('ix_hr_leave_balance_user_id'), table_name='leave_balance', schema='hr')
    op.drop_table('leave_balance', schema='hr')
    op.drop_index(op.f('ix_hr_employment_record_user_id'), table_name='employment_record', schema='hr')
    op.drop_index('ix_hr_employment_record_supervisor_id', table_name='employment_record', schema='hr')
    op.drop_index('ix_hr_employment_record_status', table_name='employment_record', schema='hr')
    op.drop_index(op.f('ix_hr_employment_record_employee_number'), table_name='employment_record', schema='hr')
    op.drop_index('ix_hr_employment_record_department_id', table_name='employment_record', schema='hr')
    op.drop_table('employment_record', schema='hr')
    op.drop_index(op.f('ix_hr_department_policy_department_id'), table_name='department_policy', schema='hr')
    op.drop_table('department_policy', schema='hr')
    op.drop_index(op.f('ix_hr_approval_authority_user_id'), table_name='approval_authority', schema='hr')
    op.drop_table('approval_authority', schema='hr')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_key'), table_name='permission')
    op.drop_table('permission')
    op.drop_table('shift_catalog', schema='hr')
    op.drop_index(op.f('ix_hr_department_name'), table_name='department', schema='hr')
    op.drop_table('department', schema='hr')
    op.execute("DROP SCHEMA IF EXISTS hr")
    # ### end Alembic commands ###
