#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    CREATE DATABASE $APP_DB_NAME OWNER $APP_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $APP_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $WXWATCH_DB_USER WITH PASSWORD '$WXWATCH_DB_PASSWORD';
    CREATE DATABASE $WXWATCH_DB_NAME OWNER $WXWATCH_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $WXWATCH_DB_NAME TO $WXWATCH_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$WXWATCH_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $WXWATCH_DB_USER;
EOSQL
