// Generated by pnpm data:build. Edit source JSON records instead.
import record0 from "@/data/source/verification/discrepancies/E-01.json";
import record1 from "@/data/source/verification/discrepancies/E-02.json";
import record2 from "@/data/source/verification/discrepancies/E-03.json";
import record3 from "@/data/source/verification/discrepancies/E-04.json";
import record4 from "@/data/source/verification/discrepancies/E-05.json";
import record5 from "@/data/source/verification/discrepancies/E-06.json";
import record6 from "@/data/source/verification/discrepancies/E-07.json";
import record7 from "@/data/source/verification/discrepancies/E-08.json";
import record8 from "@/data/source/verification/discrepancies/E-09.json";
import record9 from "@/data/source/verification/discrepancies/E-10.json";
import record10 from "@/data/source/verification/discrepancies/E-11.json";
import record11 from "@/data/source/verification/discrepancies/E-12.json";
import record12 from "@/data/source/verification/discrepancies/E-13.json";
import record13 from "@/data/source/verification/discrepancies/E-14.json";
import record14 from "@/data/source/verification/discrepancies/E-15.json";
import record15 from "@/data/source/verification/discrepancies/E-16.json";
import record16 from "@/data/source/verification/discrepancies/E-17.json";
import record17 from "@/data/source/verification/discrepancies/E-18.json";
import record18 from "@/data/source/verification/discrepancies/E-19.json";
import record19 from "@/data/source/verification/discrepancies/G-01.json";
import record20 from "@/data/source/verification/discrepancies/G-02.json";
import record21 from "@/data/source/verification/discrepancies/R-01.json";
import record22 from "@/data/source/verification/discrepancies/R-02.json";
import record23 from "@/data/source/verification/discrepancies/R-03.json";
import record24 from "@/data/source/verification/discrepancies/R-04.json";
import record25 from "@/data/source/verification/discrepancies/R-05.json";
import record26 from "@/data/source/verification/discrepancies/V-01.json";
import record27 from "@/data/source/verification/discrepancies/V-02.json";
import record28 from "@/data/source/verification/discrepancies/V-03.json";

const data = {
  items: Object.values({
    "E-01": record0,
    "E-02": record1,
    "E-03": record2,
    "E-04": record3,
    "E-05": record4,
    "E-06": record5,
    "E-07": record6,
    "E-08": record7,
    "E-09": record8,
    "E-10": record9,
    "E-11": record10,
    "E-12": record11,
    "E-13": record12,
    "E-14": record13,
    "E-15": record14,
    "E-16": record15,
    "E-17": record16,
    "E-18": record17,
    "E-19": record18,
    "G-01": record19,
    "G-02": record20,
    "R-01": record21,
    "R-02": record22,
    "R-03": record23,
    "R-04": record24,
    "R-05": record25,
    "V-01": record26,
    "V-02": record27,
    "V-03": record28,
  }),
};
export default data;
