// Generated by pnpm data:build. Edit source JSON records instead.
import record0 from "@/data/source/geography/base.json";
import record1 from "@/data/source/geography/constituencies/A.json";
import record2 from "@/data/source/geography/constituencies/B.json";
import record3 from "@/data/source/geography/constituencies/C.json";
import record4 from "@/data/source/geography/constituencies/D.json";
import record5 from "@/data/source/geography/constituencies/E.json";
import record6 from "@/data/source/geography/constituencies/F.json";
import record7 from "@/data/source/geography/constituencies/G.json";
import record8 from "@/data/source/geography/constituencies/H.json";
import record9 from "@/data/source/geography/constituencies/J.json";
import record10 from "@/data/source/geography/constituencies/K.json";
import record11 from "@/data/source/geography/constituencies/L.json";
import record12 from "@/data/source/geography/constituencies/M.json";
import record13 from "@/data/source/geography/constituencies/N.json";
import record14 from "@/data/source/geography/constituencies/P.json";
import record15 from "@/data/source/geography/constituencies/R.json";
import record16 from "@/data/source/geography/divisions/A.json";
import record17 from "@/data/source/geography/divisions/B.json";
import record18 from "@/data/source/geography/divisions/C.json";
import record19 from "@/data/source/geography/divisions/D.json";
import record20 from "@/data/source/geography/divisions/E.json";
import record21 from "@/data/source/geography/divisions/F.json";
import record22 from "@/data/source/geography/divisions/G.json";
import record23 from "@/data/source/geography/divisions/H.json";
import record24 from "@/data/source/geography/divisions/J.json";
import record25 from "@/data/source/geography/divisions/K.json";
import record26 from "@/data/source/geography/divisions/L.json";
import record27 from "@/data/source/geography/divisions/M.json";
import record28 from "@/data/source/geography/divisions/N.json";
import record29 from "@/data/source/geography/divisions/P.json";
import record30 from "@/data/source/geography/divisions/R.json";

const data = {
  ...record0,
  constituencies: {
    A: record1,
    B: record2,
    C: record3,
    D: record4,
    E: record5,
    F: record6,
    G: record7,
    H: record8,
    J: record9,
    K: record10,
    L: record11,
    M: record12,
    N: record13,
    P: record14,
    R: record15,
  },
  divisions: {
    ...record16,
    ...record17,
    ...record18,
    ...record19,
    ...record20,
    ...record21,
    ...record22,
    ...record23,
    ...record24,
    ...record25,
    ...record26,
    ...record27,
    ...record28,
    ...record29,
    ...record30,
  },
};
export default data;
