// Generated by pnpm data:build. Edit source JSON records instead.

import record1 from "@/data/source/referendums/2016/stations/A.json";
import record2 from "@/data/source/referendums/2016/stations/B.json";
import record3 from "@/data/source/referendums/2016/stations/C.json";
import record4 from "@/data/source/referendums/2016/stations/D.json";
import record5 from "@/data/source/referendums/2016/stations/E.json";
import record6 from "@/data/source/referendums/2016/stations/F.json";
import record7 from "@/data/source/referendums/2016/stations/G.json";
import record8 from "@/data/source/referendums/2016/stations/H.json";
import record9 from "@/data/source/referendums/2016/stations/J.json";
import record10 from "@/data/source/referendums/2016/stations/K.json";
import record11 from "@/data/source/referendums/2016/stations/L.json";
import record12 from "@/data/source/referendums/2016/stations/M.json";
import record13 from "@/data/source/referendums/2016/stations/N.json";
import record14 from "@/data/source/referendums/2016/stations/P.json";
import record15 from "@/data/source/referendums/2016/stations/R.json";
import record0 from "@/data/source/referendums/2016/summary.json";
import record17 from "@/data/source/referendums/2018/stations/A.json";
import record18 from "@/data/source/referendums/2018/stations/B.json";
import record19 from "@/data/source/referendums/2018/stations/C.json";
import record20 from "@/data/source/referendums/2018/stations/D.json";
import record21 from "@/data/source/referendums/2018/stations/E.json";
import record22 from "@/data/source/referendums/2018/stations/F.json";
import record23 from "@/data/source/referendums/2018/stations/G.json";
import record24 from "@/data/source/referendums/2018/stations/H.json";
import record25 from "@/data/source/referendums/2018/stations/K.json";
import record26 from "@/data/source/referendums/2018/stations/L.json";
import record27 from "@/data/source/referendums/2018/stations/M.json";
import record28 from "@/data/source/referendums/2018/stations/N.json";
import record29 from "@/data/source/referendums/2018/stations/P.json";
import record30 from "@/data/source/referendums/2018/stations/R.json";
import record16 from "@/data/source/referendums/2018/summary.json";

const data = {
  "2016": {
    ...record0,
    stations: {
      A: record1,
      B: record2,
      C: record3,
      D: record4,
      E: record5,
      F: record6,
      G: record7,
      H: record8,
      J: record9,
      K: record10,
      L: record11,
      M: record12,
      N: record13,
      P: record14,
      R: record15,
    },
  },
  "2018": {
    ...record16,
    stations: {
      A: record17,
      B: record18,
      C: record19,
      D: record20,
      E: record21,
      F: record22,
      G: record23,
      H: record24,
      K: record25,
      L: record26,
      M: record27,
      N: record28,
      P: record29,
      R: record30,
    },
  },
};
export default data;
