// Generated by pnpm data:build. Edit source JSON records instead.

import record16 from "@/data/source/register/addenda/2020-06-30.json";
import record17 from "@/data/source/register/addenda/2020-09-30.json";
import record18 from "@/data/source/register/addenda/2021-03-31.json";
import record19 from "@/data/source/register/addenda/2021-06-30.json";
import record20 from "@/data/source/register/addenda/2021-09-30.json";
import record21 from "@/data/source/register/addenda/2021-12-31.json";
import record22 from "@/data/source/register/addenda/2022-03-31.json";
import record23 from "@/data/source/register/addenda/2022-05-27.json";
import record24 from "@/data/source/register/addenda/2022-09-30.json";
import record25 from "@/data/source/register/addenda/2023-06-30.json";
import record26 from "@/data/source/register/addenda/2023-09-30.json";
import record27 from "@/data/source/register/addenda/2023-12-31.json";
import record28 from "@/data/source/register/addenda/2024-03-31.json";
import record29 from "@/data/source/register/addenda/2024-06-30.json";
import record30 from "@/data/source/register/addenda/2024-09-30.json";
import record31 from "@/data/source/register/addenda/2024-12-31.json";
import record32 from "@/data/source/register/addenda/2025-03-31.json";
import record33 from "@/data/source/register/addenda/2025-06-30.json";
import record34 from "@/data/source/register/addenda/2025-09-30.json";
import record35 from "@/data/source/register/addenda/2025-12-31.json";
import record36 from "@/data/source/register/addenda/2026-03-31.json";
import record37 from "@/data/source/register/addenda/2026-06-30.json";
import record0 from "@/data/source/register/metadata.json";
import record1 from "@/data/source/register/snapshots/2019-12-31.json";
import record2 from "@/data/source/register/snapshots/2020-06-30.json";
import record3 from "@/data/source/register/snapshots/2020-12-31.json";
import record4 from "@/data/source/register/snapshots/2021-06-30.json";
import record5 from "@/data/source/register/snapshots/2021-12-31.json";
import record6 from "@/data/source/register/snapshots/2022-05-27.json";
import record7 from "@/data/source/register/snapshots/2022-06-10.json";
import record8 from "@/data/source/register/snapshots/2022-12-31.json";
import record9 from "@/data/source/register/snapshots/2023-06-30.json";
import record10 from "@/data/source/register/snapshots/2023-12-31.json";
import record11 from "@/data/source/register/snapshots/2024-06-30.json";
import record12 from "@/data/source/register/snapshots/2024-12-31.json";
import record13 from "@/data/source/register/snapshots/2025-06-30.json";
import record14 from "@/data/source/register/snapshots/2025-12-31.json";
import record15 from "@/data/source/register/snapshots/2026-06-30.json";

const data = {
  ...record0,
  snapshots: Object.values({
    "2019-12-31": record1,
    "2020-06-30": record2,
    "2020-12-31": record3,
    "2021-06-30": record4,
    "2021-12-31": record5,
    "2022-05-27": record6,
    "2022-06-10": record7,
    "2022-12-31": record8,
    "2023-06-30": record9,
    "2023-12-31": record10,
    "2024-06-30": record11,
    "2024-12-31": record12,
    "2025-06-30": record13,
    "2025-12-31": record14,
    "2026-06-30": record15,
  }),
  addenda: Object.values({
    "2020-06-30": record16,
    "2020-09-30": record17,
    "2021-03-31": record18,
    "2021-06-30": record19,
    "2021-09-30": record20,
    "2021-12-31": record21,
    "2022-03-31": record22,
    "2022-05-27": record23,
    "2022-09-30": record24,
    "2023-06-30": record25,
    "2023-09-30": record26,
    "2023-12-31": record27,
    "2024-03-31": record28,
    "2024-06-30": record29,
    "2024-09-30": record30,
    "2024-12-31": record31,
    "2025-03-31": record32,
    "2025-06-30": record33,
    "2025-09-30": record34,
    "2025-12-31": record35,
    "2026-03-31": record36,
    "2026-06-30": record37,
  }),
};
export default data;
