#make_db.config. Please do not alter this file unless otherwise instructed!
database_name=CIMH_RASP_AWS.db
setup=CREATE TABLE CIMH_SOIL(ID INTEGER PRIMARY KEY,STATION_Name CHARACTER,STATION_ID INTEGER,RECORD_DATE DATETIME,SM DECIMAL(4,2),ST DECIMAL(4,2),EC DECIMAL(4,2),SP DECIMAL(4,2))
