#db_ingester.conf Please do not alter this file unless instructed to!
file_path=/home/data/Sutron_Linux/FTP_Files/
database_path=/home/data/Sutron_Linux/Database/
database_name=/home/data/Sutron_Linux/Database/make_db.conf
file_name=/home/data/Sutron_Linux/FTP_Files/test_filename.txt
divisor=100
station_ID=13000

