#db_ingester.conf Please do not alter this file unless instructed to!
file_path=/home/pi/Sutron_Linux/FTP_Files/
database_path=/home/pi/Sutron_Linux/Database/
database_name=/home/pi/Sutron_Linux/Database/make_db.conf
file_name=arguments
divisor=1000
station_ID=10001

