"""Load the small authoritative JSON records and assemble website import modules.

No network, database, or original prototype checkout is needed.
"""

import json
from pathlib import Path

APP = Path(__file__).resolve().parents[2]
SOURCE = APP / "src/data/source"
GENERATED = APP / "src/data/derived"


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


class Archive:
    """One traversal supplies Python exports and static TypeScript imports."""

    def __init__(self):
        self.modules = {}
        self.inputs = set()
        self.imports = []

    def record(self, relative):
        path = SOURCE / relative
        self.inputs.add(path)
        name = f"record{len(self.imports)}"
        self.imports.append(f'import {name} from "@/data/source/{relative}";')
        return read(path), name

    def group(self, pattern):
        values, expressions = {}, []
        for path in sorted(SOURCE.glob(pattern)):
            value, expression = self.record(path.relative_to(SOURCE).as_posix())
            values[path.stem] = value
            expressions.append(f"{json.dumps(path.stem)}: {expression}")
        return values, "{" + ",\n".join(expressions) + "}"

    def save(self, name, expression):
        self.modules[name] = (
            "// Generated by pnpm data:build. Edit source JSON records instead.\n"
            + "\n".join(self.imports)
            + f"\nconst data = {expression};\nexport default data;\n"
        )
        self.imports = []

    def results(self):
        names, names_expr = self.record("reference/constituencies.json")
        corrections, corrections_expr = self.record("verification/corrections.json")
        values = dict(
            cons=names, early={}, results={}, national={}, stations={}, **corrections
        )
        expressions = {key: [] for key in ("early", "results", "national", "stations")}
        events = read(SOURCE / "reference/events.json")
        for event in events:
            if event["kind"] != "general":
                continue
            year = event["id"]
            value, expr = self.record(f"elections/{year}/results.json")
            key = "results" if event["mapped"] else "early"
            values[key][year] = value
            expressions[key].append(f'"{year}": {expr}')
            if (SOURCE / f"elections/{year}/national.json").exists():
                value, expr = self.record(f"elections/{year}/national.json")
                values["national"][year] = value
                expressions["national"].append(f'"{year}": {expr}')
            stations, expr = self.group(f"elections/{year}/stations/*.json")
            if stations:
                values["stations"][year] = stations
                expressions["stations"].append(f'"{year}": {expr}')
        expr = (
            f"{{cons: {names_expr}, ...{corrections_expr},"
            + ",".join(
                key + ": {" + ",".join(rows) + "}" for key, rows in expressions.items()
            )
            + "}"
        )
        self.save("results", expr)
        return values

    def referendum(self):
        values, expressions = {}, []
        for folder in sorted((SOURCE / "referendums").iterdir()):
            summary, expr = self.record(f"referendums/{folder.name}/summary.json")
            stations, station_expr = self.group(
                f"referendums/{folder.name}/stations/*.json"
            )
            values[folder.name] = dict(summary, stations=stations)
            expressions.append(
                f'"{folder.name}": {{...{expr}, stations: {station_expr}}}'
            )
        self.save("referendum", "{" + ",".join(expressions) + "}")
        return values

    def geo(self):
        base, base_expr = self.record("geography/base.json")
        constituencies, cons_expr = self.group("geography/constituencies/*.json")
        divisions, div_expr = {}, []
        for path in sorted(SOURCE.glob("geography/divisions/*.json")):
            value, expr = self.record(path.relative_to(SOURCE).as_posix())
            divisions.update(value)
            div_expr.append("..." + expr)
        self.save(
            "geo",
            f"{{...{base_expr}, constituencies: {cons_expr}, divisions: {{"
            + ",".join(div_expr)
            + "}}",
        )
        return dict(base, constituencies=constituencies, divisions=divisions)

    def register(self):
        data, expr = self.record("register/metadata.json")
        expressions = ["..." + expr]
        for kind in ("snapshots", "addenda"):
            values, expr = self.group(f"register/{kind}/*.json")
            data[kind] = list(values.values())
            expressions.append(f"{kind}: Object.values({expr})")
        self.save("register", "{" + ",".join(expressions) + "}")
        return data

    def discrepancies(self):
        items, expr = self.group("verification/discrepancies/*.json")
        self.save("discrepancies", f"{{items: Object.values({expr})}}")
        return {"items": list(items.values())}
