import { PageHeader } from "@/components/page-header";
import { InfoTable } from "@/components/pages/info-table";
import { PageSection } from "@/components/pages/page-section";

export const metadata = {
  title: "Weather glossary",
  description:
    "The terms used in Grenada Meteorological Service forecasts and warnings, explained.",
};

export default function GlossaryPage() {
  return (
    <>
      <PageHeader
        description="The terms we use in forecasts and warnings."
        title="Weather glossary"
      />
      <PageSection heading="Warnings and products">
        <InfoTable
          headers={["Term", "Meaning"]}
          rows={[
            [
              "Advisory",
              "Conditions that are hazardous for some users or activities, below warning level",
            ],
            ["Watch", "Hazardous conditions are likely; prepare"],
            [
              "Warning",
              "Hazardous conditions are expected or occurring; act now",
            ],
            [
              "CAP",
              "Common Alerting Protocol — the structured format warnings are published in",
            ],
            [
              "METAR",
              "Routine hourly observation of conditions at an aerodrome",
            ],
            [
              "TAF",
              "Terminal Aerodrome Forecast — forecast conditions at an aerodrome",
            ],
            [
              "Synopsis",
              "The forecaster's summary of the overall weather pattern",
            ],
          ]}
        />
      </PageSection>
      <PageSection heading="Tropical systems">
        <InfoTable
          headers={["Term", "Meaning"]}
          rows={[
            [
              "Tropical wave",
              "A trough moving west across the Atlantic; the most common cause of showery spells in Grenada",
            ],
            [
              "Tropical depression",
              "A closed circulation with winds up to 33 kt",
            ],
            [
              "Tropical storm",
              "Winds of 34 to 63 kt; the system is named at this stage",
            ],
            ["Hurricane", "Winds of 64 kt or more"],
            ["Major hurricane", "Category 3 or above — winds of 96 kt or more"],
            [
              "Storm surge",
              "Sea water pushed onshore by a storm's wind and low pressure",
            ],
            [
              "Eye",
              "The calm centre of a hurricane; the wind returns from the opposite direction after it passes",
            ],
          ]}
        />
      </PageSection>
      <PageSection heading="Rain, wind and sea">
        <InfoTable
          headers={["Term", "Meaning"]}
          rows={[
            ["Isolated", "Affecting less than about a quarter of the area"],
            ["Scattered", "Affecting roughly a quarter to a half of the area"],
            ["Widespread", "Affecting most of the area"],
            ["Knot (kt)", "One nautical mile per hour — about 1.85 km/h"],
            [
              "Significant wave height",
              "The average height of the highest third of waves",
            ],
            [
              "Swell",
              "Waves generated by distant weather, arriving with a long period",
            ],
            [
              "Trade winds",
              "The steady east-north-easterly flow that dominates Grenada's weather",
            ],
            [
              "Saharan dust",
              "Mineral dust carried across the Atlantic, hazing the sky and raising particulate levels",
            ],
          ]}
        />
      </PageSection>
    </>
  );
}
