/* biome-ignore-all lint: Generated by Payload; regenerate instead of editing. */
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'desk-updates': DeskUpdate;
    stories: Story;
    publications: Publication;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'desk-updates': DeskUpdatesSelect<false> | DeskUpdatesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * From the Desk: product changes, service notices and announcements. Never a forecast or a warning; those are issued in the forecast system.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desk-updates".
 */
export interface DeskUpdate {
  id: number;
  title: string;
  kind: 'product-update' | 'service-update' | 'announcement' | 'public-notice' | 'community-update';
  /**
   * The product this update is about, if any.
   */
  product?: ('tropical-outlook' | 'bulletins' | 'forecasts' | 'marine' | 'aviation' | 'cap') | null;
  /**
   * Shown on cards and in search. 200 characters at most.
   */
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?: ('X' | 'Facebook' | 'Instagram' | 'YouTube' | 'LinkedIn' | 'WhatsApp Channel')[] | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category: 'forecast' | 'cap' | 'aviation' | 'bulletin' | 'publication' | 'article' | 'source';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  author: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Identity comes from FastAPI. Only the CMS editorial role is managed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fastapiUserId: string;
  username: string;
  email: string;
  permissionKeys?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isSuperuser?: boolean | null;
  role: 'author' | 'editor';
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * Stories from our atmosphere and ocean: features that explain the weather, the sea and the climate around us.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  title: string;
  /**
   * Short label above the headline.
   */
  kicker?: string | null;
  kind: 'local-story' | 'weather-event' | 'climate' | 'ocean' | 'explainer' | 'community';
  /**
   * Shown on cards and in search. 240 characters at most.
   */
  summary: string;
  /**
   * Shown on cards and at the top of the page.
   */
  image: number | Media;
  imageCaption?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used to link related questions, stories and reports.
   */
  topics?:
    | ('tropical' | 'rain' | 'heat' | 'marine' | 'climate' | 'sky' | 'safety' | 'agriculture' | 'aviation' | 'gms')[]
    | null;
  /**
   * Optional. Falls back to the title, summary and image.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?: ('X' | 'Facebook' | 'Instagram' | 'YouTube' | 'LinkedIn' | 'WhatsApp Channel')[] | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category: 'forecast' | 'cap' | 'aviation' | 'bulletin' | 'publication' | 'article' | 'source';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  author: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and documents for GMS website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text shown to screen readers.
   */
  alt: string;
  /**
   * Who made or supplied it, e.g. "GMS / J. Pryce" or "NOAA".
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Latest reports: climate summaries, outlooks, reports and datasets. Each has the document itself and the period it covers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  type: 'report' | 'climate-bulletin' | 'outlook' | 'guide' | 'dataset' | 'policy' | 'research';
  /**
   * Groups regular reports so readers can browse them.
   */
  series?: ('monthly-climate' | 'seasonal-outlook' | 'hurricane-season' | 'annual-report') | null;
  /**
   * The PDF, CSV or spreadsheet itself.
   */
  document: number | Media;
  periodStart?: string | null;
  periodEnd?: string | null;
  /**
   * Shown on cards and in search. 280 characters at most.
   */
  summary: string;
  /**
   * Up to three one-line findings for the card.
   */
  keyFindings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on cards and at the top of the page.
   */
  image?: (number | null) | Media;
  imageCaption?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Used to link related questions, stories and reports.
   */
  topics?:
    | ('tropical' | 'rain' | 'heat' | 'marine' | 'climate' | 'sky' | 'safety' | 'agriculture' | 'aviation' | 'gms')[]
    | null;
  /**
   * Optional. Falls back to the title, summary and image.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?: ('X' | 'Facebook' | 'Instagram' | 'YouTube' | 'LinkedIn' | 'WhatsApp Channel')[] | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category: 'forecast' | 'cap' | 'aviation' | 'bulletin' | 'publication' | 'article' | 'source';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: 'draft' | 'review' | 'published';
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  author: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'desk-updates';
        value: number | DeskUpdate;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desk-updates_select".
 */
export interface DeskUpdatesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  product?: T;
  summary?: T;
  body?: T;
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  title?: T;
  kicker?: T;
  kind?: T;
  summary?: T;
  image?: T;
  imageCaption?: T;
  body?: T;
  topics?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  series?: T;
  document?: T;
  periodStart?: T;
  periodEnd?: T;
  summary?: T;
  keyFindings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  imageCaption?: T;
  body?: T;
  topics?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fastapiUserId?: T;
  username?: T;
  email?: T;
  permissionKeys?: T;
  isSuperuser?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}