import path from "node:path";
import { fileURLToPath } from "node:url";
import { postgresAdapter } from "@payloadcms/db-postgres";
import { buildConfig } from "payload";
import { Content } from "./collections/content";
import { Users } from "./collections/users";
import { getEnv } from "./env";

const env = getEnv();
const baseDir = path.dirname(fileURLToPath(import.meta.url));
export default buildConfig({
  secret: env.PAYLOAD_SECRET,
  db: postgresAdapter({ pool: { connectionString: env.DATABASE_URL } }),
  admin: {
    user: "users",
    components: {
      logout: { Button: "/components/logout-button#LogoutButton" },
    },
    importMap: { baseDir },
    meta: { titleSuffix: " | GMS Content" },
  },
  collections: [Users, Content],
  graphQL: { disable: true },
  typescript: {
    postProcess: [
      ({ compiledTypes }) =>
        "/* biome-ignore-all lint: Generated by Payload; regenerate instead of editing. */\n" +
        compiledTypes,
    ],
    outputFile: path.resolve(baseDir, "payload-types.ts"),
  },
});
