/* biome-ignore-all lint: Generated by Payload; regenerate instead of editing. */
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    "desk-updates": DeskUpdate;
    stories: Story;
    questions: Question;
    publications: Publication;
    media: Media;
    users: User;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    "desk-updates": DeskUpdatesSelect<false> | DeskUpdatesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    "weather-now": WeatherNow;
    homepage: Homepage;
  };
  globalsSelect: {
    "weather-now": WeatherNowSelect<false> | WeatherNowSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  locale: null;
  user: User;
  widgets: {
    collections: CollectionsWidget;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * From the Desk: product changes, service notices and announcements. Never a forecast or a warning; those are issued in the forecast system.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desk-updates".
 */
export interface DeskUpdate {
  author: number | User;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createdAt: string;
  id: number;
  kind:
    | "product-update"
    | "service-update"
    | "announcement"
    | "public-notice"
    | "community-update";
  /**
   * The product this update is about, if any.
   */
  product?:
    | (
        | "tropical-outlook"
        | "bulletins"
        | "forecasts"
        | "marine"
        | "aviation"
        | "cap"
      )
    | null;
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category:
          | "forecast"
          | "cap"
          | "aviation"
          | "bulletin"
          | "publication"
          | "article"
          | "source";
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?:
      | (
          | "X"
          | "Facebook"
          | "Instagram"
          | "YouTube"
          | "LinkedIn"
          | "WhatsApp Channel"
        )[]
      | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: "draft" | "review" | "published";
  /**
   * Shown on cards and in search. 200 characters at most.
   */
  summary: string;
  title: string;
  updatedAt: string;
}
/**
 * Identity comes from FastAPI. Only the CMS editorial role is managed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  collection: "users";
  createdAt: string;
  email: string;
  fastapiUserId: string;
  id: number;
  isSuperuser?: boolean | null;
  permissionKeys?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  role: "author" | "editor";
  updatedAt: string;
  username: string;
}
/**
 * Stories from our atmosphere and ocean: features that explain the weather, the sea and the climate around us.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  author: number | User;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  createdAt: string;
  id: number;
  /**
   * Shown on cards and at the top of the page.
   */
  image: number | Media;
  imageCaption?: string | null;
  /**
   * Short label above the headline.
   */
  kicker?: string | null;
  kind:
    | "local-story"
    | "weather-event"
    | "climate"
    | "ocean"
    | "explainer"
    | "community";
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category:
          | "forecast"
          | "cap"
          | "aviation"
          | "bulletin"
          | "publication"
          | "article"
          | "source";
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Falls back to the title, summary and image.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?:
      | (
          | "X"
          | "Facebook"
          | "Instagram"
          | "YouTube"
          | "LinkedIn"
          | "WhatsApp Channel"
        )[]
      | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: "draft" | "review" | "published";
  /**
   * Shown on cards and in search. 240 characters at most.
   */
  summary: string;
  title: string;
  /**
   * Used to link related questions, stories and reports.
   */
  topics?:
    | (
        | "tropical"
        | "rain"
        | "heat"
        | "marine"
        | "climate"
        | "sky"
        | "safety"
        | "agriculture"
        | "aviation"
        | "gms"
      )[]
    | null;
  updatedAt: string;
}
/**
 * Images and documents for GMS website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  /**
   * Alt text shown to screen readers.
   */
  alt: string;
  createdAt: string;
  /**
   * Who made or supplied it, e.g. "GMS / J. Pryce" or "NOAA".
   */
  credit?: string | null;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  height?: number | null;
  id: number;
  mimeType?: string | null;
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  width?: number | null;
}
/**
 * Questions about the weather: the questions people ask, each with a short answer and a full explainer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  author: number | User;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  createdAt: string;
  id: number;
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  /**
   * Phrase it the way the public asks it.
   */
  question: string;
  /**
   * Other questions, stories or reports to read next.
   */
  related?:
    | (
        | {
            relationTo: "questions";
            value: number | Question;
          }
        | {
            relationTo: "stories";
            value: number | Story;
          }
        | {
            relationTo: "publications";
            value: number | Publication;
          }
      )[]
    | null;
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category:
          | "forecast"
          | "cap"
          | "aviation"
          | "bulletin"
          | "publication"
          | "article"
          | "source";
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A meteorologist confirms the answer is correct.
   */
  scienceCheck?: {
    checked?: boolean | null;
    checkedAt?: string | null;
    checkedBy?: (number | null) | User;
  };
  /**
   * Optional. Falls back to the title, summary and image.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Two or three plain sentences. Shown on the homepage and in search.
   */
  shortAnswer: string;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: "draft" | "review" | "published";
  /**
   * Used to link related questions, stories and reports.
   */
  topics?:
    | (
        | "tropical"
        | "rain"
        | "heat"
        | "marine"
        | "climate"
        | "sky"
        | "safety"
        | "agriculture"
        | "aviation"
        | "gms"
      )[]
    | null;
  updatedAt: string;
}
/**
 * Latest reports: climate summaries, outlooks, reports and datasets. Each has the document itself and the period it covers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  author: number | User;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  createdAt: string;
  /**
   * The PDF, CSV or spreadsheet itself.
   */
  document: number | Media;
  id: number;
  /**
   * Shown on cards and at the top of the page.
   */
  image?: (number | null) | Media;
  imageCaption?: string | null;
  /**
   * Up to three one-line findings for the card.
   */
  keyFindings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  periodEnd?: string | null;
  periodStart?: string | null;
  /**
   * Set when first published; used for ordering and the URL.
   */
  publishedAt?: string | null;
  /**
   * Link to an existing product, publication or news source. Linking does not publish the destination.
   */
  relatedLinks?:
    | {
        title: string;
        category:
          | "forecast"
          | "cap"
          | "aviation"
          | "bulletin"
          | "publication"
          | "article"
          | "source";
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Falls back to the title, summary and image.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Groups regular reports so readers can browse them.
   */
  series?:
    | (
        | "monthly-climate"
        | "seasonal-outlook"
        | "hurricane-season"
        | "annual-report"
      )
    | null;
  /**
   * Built from the title. Fixed once published so links last.
   */
  slug: string;
  /**
   * Prepare platform-specific copy. Automatic delivery can be added later.
   */
  social?: {
    caption?: string | null;
    enabledPlatforms?:
      | (
          | "X"
          | "Facebook"
          | "Instagram"
          | "YouTube"
          | "LinkedIn"
          | "WhatsApp Channel"
        )[]
      | null;
    /**
     * Leave empty for manual or immediate sharing.
     */
    publishAt?: string | null;
    xText?: string | null;
    facebookText?: string | null;
    instagramText?: string | null;
    linkedinText?: string | null;
    whatsappText?: string | null;
  };
  /**
   * Save as Ready for review. An editor with this section's permission publishes.
   */
  status: "draft" | "review" | "published";
  /**
   * Shown on cards and in search. 280 characters at most.
   */
  summary: string;
  title: string;
  /**
   * Used to link related questions, stories and reports.
   */
  topics?:
    | (
        | "tropical"
        | "rain"
        | "heat"
        | "marine"
        | "climate"
        | "sky"
        | "safety"
        | "agriculture"
        | "aviation"
        | "gms"
      )[]
    | null;
  type:
    | "report"
    | "climate-bulletin"
    | "outlook"
    | "guide"
    | "dataset"
    | "policy"
    | "research";
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id: number;
  key: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  createdAt: string;
  document?:
    | ({
        relationTo: "desk-updates";
        value: number | DeskUpdate;
      } | null)
    | ({
        relationTo: "stories";
        value: number | Story;
      } | null)
    | ({
        relationTo: "questions";
        value: number | Question;
      } | null)
    | ({
        relationTo: "publications";
        value: number | Publication;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null);
  globalSlug?: string | null;
  id: number;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: number | User;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  createdAt: string;
  id: number;
  key?: string | null;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: number | User;
  };
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  batch?: number | null;
  createdAt: string;
  id: number;
  name?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "desk-updates_select".
 */
export interface DeskUpdatesSelect<T extends boolean = true> {
  author?: T;
  body?: T;
  createdAt?: T;
  kind?: T;
  product?: T;
  publishedAt?: T;
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  status?: T;
  summary?: T;
  title?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  author?: T;
  body?: T;
  createdAt?: T;
  image?: T;
  imageCaption?: T;
  kicker?: T;
  kind?: T;
  publishedAt?: T;
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  status?: T;
  summary?: T;
  title?: T;
  topics?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  author?: T;
  body?: T;
  createdAt?: T;
  publishedAt?: T;
  question?: T;
  related?: T;
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  scienceCheck?:
    | T
    | {
        checked?: T;
        checkedAt?: T;
        checkedBy?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  shortAnswer?: T;
  slug?: T;
  status?: T;
  topics?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  author?: T;
  body?: T;
  createdAt?: T;
  document?: T;
  image?: T;
  imageCaption?: T;
  keyFindings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  periodEnd?: T;
  periodStart?: T;
  publishedAt?: T;
  relatedLinks?:
    | T
    | {
        title?: T;
        category?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  series?: T;
  slug?: T;
  social?:
    | T
    | {
        caption?: T;
        enabledPlatforms?: T;
        publishAt?: T;
        xText?: T;
        facebookText?: T;
        instagramText?: T;
        linkedinText?: T;
        whatsappText?: T;
      };
  status?: T;
  summary?: T;
  title?: T;
  topics?: T;
  type?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdAt?: T;
  credit?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  height?: T;
  mimeType?: T;
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdAt?: T;
  email?: T;
  fastapiUserId?: T;
  isSuperuser?: T;
  permissionKeys?: T;
  role?: T;
  updatedAt?: T;
  username?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  data?: T;
  key?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  createdAt?: T;
  document?: T;
  globalSlug?: T;
  updatedAt?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  createdAt?: T;
  key?: T;
  updatedAt?: T;
  user?: T;
  value?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  batch?: T;
  createdAt?: T;
  name?: T;
  updatedAt?: T;
}
/**
 * The duty forecaster's short note and the imagery cards on the homepage. The note is a plain-words aside, never a forecast or a warning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-now".
 */
export interface WeatherNow {
  createdAt?: string | null;
  id: number;
  /**
   * Up to four live imagery cards. Editors manage these.
   */
  imagery?:
    | {
        layer: "satellite" | "radar" | "rainfall" | "lightning";
        title: string;
        /**
         * A still image, or leave empty and give a feed URL.
         */
        image?: (number | null) | Media;
        imageUrl?: string | null;
        /**
         * The site page to open, e.g. /weather/radar.
         */
        href: string;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  note?: {
    /**
     * Two or three plain sentences, e.g. what to expect this afternoon. Published as soon as you save. Clear it to remove the note.
     */
    text?: string | null;
    /**
     * Required only if the note mentions a warning, watch or advisory.
     */
    alertUrl?: string | null;
    /**
     * Defaults to the next forecast issue (07:00, 12:00 or 18:00).
     */
    expiresAt?: string | null;
    postedAt?: string | null;
    postedBy?: (number | null) | User;
  };
  updatedAt?: string | null;
}
/**
 * Choose what leads each homepage section, or hide a section (for example during a hurricane). Anything left empty shows the newest published items.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  createdAt?: string | null;
  /**
   * Which cards Sky, history and a little fun shows.
   */
  discoverCards?: ("sky" | "on-this-day" | "quiz" | "fact")[] | null;
  /**
   * Shown first in Latest reports.
   */
  featuredPublication?: (number | null) | Publication;
  /**
   * Up to five, in order. Default: the newest.
   */
  featuredQuestions?: (number | Question)[] | null;
  /**
   * Sections to hide from the homepage for now.
   */
  hiddenSections?:
    | (
        | "weather-now"
        | "desk"
        | "stories"
        | "questions"
        | "discover"
        | "reports"
      )[]
    | null;
  id: number;
  /**
   * The large story. Default: the newest.
   */
  leadStory?: (number | null) | Story;
  updatedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-now_select".
 */
export interface WeatherNowSelect<T extends boolean = true> {
  createdAt?: T;
  globalType?: T;
  imagery?:
    | T
    | {
        layer?: T;
        title?: T;
        image?: T;
        imageUrl?: T;
        href?: T;
        credit?: T;
        id?: T;
      };
  note?:
    | T
    | {
        text?: T;
        alertUrl?: T;
        expiresAt?: T;
        postedAt?: T;
        postedBy?: T;
      };
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  createdAt?: T;
  discoverCards?: T;
  featuredPublication?: T;
  featuredQuestions?: T;
  globalType?: T;
  hiddenSections?: T;
  leadStory?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
