// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemImageCreate
 */
export type ItemImageCreate = {
    /**
     * Alt Text
     */
    alt_text?: string | null;
    /**
     * Object Key
     */
    object_key: string;
};

/**
 * ItemImagePublic
 */
export type ItemImagePublic = {
    /**
     * Alt Text
     */
    alt_text?: string | null;
    /**
     * Object Key
     */
    object_key: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Item Id
     */
    item_id: string;
};

/**
 * ItemImagesPublic
 */
export type ItemImagesPublic = {
    /**
     * Data
     */
    data: Array<ItemImagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<Item>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PermissionCreate
 */
export type PermissionCreate = {
    /**
     * Action
     */
    action: string;
    /**
     * Entity
     */
    entity: string;
    /**
     * Access
     */
    access: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * PermissionPublic
 */
export type PermissionPublic = {
    /**
     * Action
     */
    action: string;
    /**
     * Entity
     */
    entity: string;
    /**
     * Access
     */
    access: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PermissionsPublic
 */
export type PermissionsPublic = {
    /**
     * Data
     */
    data: Array<PermissionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
};

/**
 * RolePublic
 */
export type RolePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RolesPublic
 */
export type RolesPublic = {
    /**
     * Data
     */
    data: Array<RolePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Full Name
     */
    full_name: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Username
     */
    username?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Middle Name
     */
    middle_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Incorrect email/password or inactive user
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Login successful, access token returned
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type TestTokenApiV1LoginTestTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type TestTokenApiV1LoginTestTokenPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestTokenApiV1LoginTestTokenPostResponse = TestTokenApiV1LoginTestTokenPostResponses[keyof TestTokenApiV1LoginTestTokenPostResponses];

export type RecoverPasswordApiV1PasswordRecoveryEmailPostData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostError = RecoverPasswordApiV1PasswordRecoveryEmailPostErrors[keyof RecoverPasswordApiV1PasswordRecoveryEmailPostErrors];

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordApiV1PasswordRecoveryEmailPostResponse = RecoverPasswordApiV1PasswordRecoveryEmailPostResponses[keyof RecoverPasswordApiV1PasswordRecoveryEmailPostResponses];

export type ResetPasswordApiV1ResetPasswordPostData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type ResetPasswordApiV1ResetPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordApiV1ResetPasswordPostError = ResetPasswordApiV1ResetPasswordPostErrors[keyof ResetPasswordApiV1ResetPasswordPostErrors];

export type ResetPasswordApiV1ResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordApiV1ResetPasswordPostResponse = ResetPasswordApiV1ResetPasswordPostResponses[keyof ResetPasswordApiV1ResetPasswordPostResponses];

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostError = RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostErrors[keyof RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostErrors];

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponse = RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponses[keyof RecoverPasswordHtmlContentApiV1PasswordRecoveryHtmlContentEmailPostResponses];

export type ReadUsersApiV1AuthUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/auth/users/';
};

export type ReadUsersApiV1AuthUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersApiV1AuthUsersGetError = ReadUsersApiV1AuthUsersGetErrors[keyof ReadUsersApiV1AuthUsersGetErrors];

export type ReadUsersApiV1AuthUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersApiV1AuthUsersGetResponse = ReadUsersApiV1AuthUsersGetResponses[keyof ReadUsersApiV1AuthUsersGetResponses];

export type CreateUserApiV1AuthUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/';
};

export type CreateUserApiV1AuthUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AuthUsersPostError = CreateUserApiV1AuthUsersPostErrors[keyof CreateUserApiV1AuthUsersPostErrors];

export type CreateUserApiV1AuthUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserApiV1AuthUsersPostResponse = CreateUserApiV1AuthUsersPostResponses[keyof CreateUserApiV1AuthUsersPostResponses];

export type DeleteUserMeApiV1AuthUsersMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type DeleteUserMeApiV1AuthUsersMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeApiV1AuthUsersMeDeleteResponse = DeleteUserMeApiV1AuthUsersMeDeleteResponses[keyof DeleteUserMeApiV1AuthUsersMeDeleteResponses];

export type ReadUserMeApiV1AuthUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type ReadUserMeApiV1AuthUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserMeApiV1AuthUsersMeGetResponse = ReadUserMeApiV1AuthUsersMeGetResponses[keyof ReadUserMeApiV1AuthUsersMeGetResponses];

export type UpdateUserMeApiV1AuthUsersMePatchData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type UpdateUserMeApiV1AuthUsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeApiV1AuthUsersMePatchError = UpdateUserMeApiV1AuthUsersMePatchErrors[keyof UpdateUserMeApiV1AuthUsersMePatchErrors];

export type UpdateUserMeApiV1AuthUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserMeApiV1AuthUsersMePatchResponse = UpdateUserMeApiV1AuthUsersMePatchResponses[keyof UpdateUserMeApiV1AuthUsersMePatchResponses];

export type UpdatePasswordMeApiV1AuthUsersMePasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me/password';
};

export type UpdatePasswordMeApiV1AuthUsersMePasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeApiV1AuthUsersMePasswordPatchError = UpdatePasswordMeApiV1AuthUsersMePasswordPatchErrors[keyof UpdatePasswordMeApiV1AuthUsersMePasswordPatchErrors];

export type UpdatePasswordMeApiV1AuthUsersMePasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeApiV1AuthUsersMePasswordPatchResponse = UpdatePasswordMeApiV1AuthUsersMePasswordPatchResponses[keyof UpdatePasswordMeApiV1AuthUsersMePasswordPatchResponses];

export type RegisterUserApiV1AuthUsersSignupPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/signup';
};

export type RegisterUserApiV1AuthUsersSignupPostErrors = {
    /**
     * User with this email already exists
     */
    400: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiV1AuthUsersSignupPostError = RegisterUserApiV1AuthUsersSignupPostErrors[keyof RegisterUserApiV1AuthUsersSignupPostErrors];

export type RegisterUserApiV1AuthUsersSignupPostResponses = {
    /**
     * User registered successfully
     */
    201: UserPublic;
};

export type RegisterUserApiV1AuthUsersSignupPostResponse = RegisterUserApiV1AuthUsersSignupPostResponses[keyof RegisterUserApiV1AuthUsersSignupPostResponses];

export type DeleteUserApiV1AuthUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type DeleteUserApiV1AuthUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1AuthUsersUserIdDeleteError = DeleteUserApiV1AuthUsersUserIdDeleteErrors[keyof DeleteUserApiV1AuthUsersUserIdDeleteErrors];

export type DeleteUserApiV1AuthUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserApiV1AuthUsersUserIdDeleteResponse = DeleteUserApiV1AuthUsersUserIdDeleteResponses[keyof DeleteUserApiV1AuthUsersUserIdDeleteResponses];

export type ReadUserByIdApiV1AuthUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type ReadUserByIdApiV1AuthUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdApiV1AuthUsersUserIdGetError = ReadUserByIdApiV1AuthUsersUserIdGetErrors[keyof ReadUserByIdApiV1AuthUsersUserIdGetErrors];

export type ReadUserByIdApiV1AuthUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdApiV1AuthUsersUserIdGetResponse = ReadUserByIdApiV1AuthUsersUserIdGetResponses[keyof ReadUserByIdApiV1AuthUsersUserIdGetResponses];

export type UpdateUserApiV1AuthUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{user_id}';
};

export type UpdateUserApiV1AuthUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1AuthUsersUserIdPatchError = UpdateUserApiV1AuthUsersUserIdPatchErrors[keyof UpdateUserApiV1AuthUsersUserIdPatchErrors];

export type UpdateUserApiV1AuthUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiV1AuthUsersUserIdPatchResponse = UpdateUserApiV1AuthUsersUserIdPatchResponses[keyof UpdateUserApiV1AuthUsersUserIdPatchResponses];

export type ReadRolesApiV1AuthRolesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/auth/roles/';
};

export type ReadRolesApiV1AuthRolesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRolesApiV1AuthRolesGetError = ReadRolesApiV1AuthRolesGetErrors[keyof ReadRolesApiV1AuthRolesGetErrors];

export type ReadRolesApiV1AuthRolesGetResponses = {
    /**
     * Successful Response
     */
    200: RolesPublic;
};

export type ReadRolesApiV1AuthRolesGetResponse = ReadRolesApiV1AuthRolesGetResponses[keyof ReadRolesApiV1AuthRolesGetResponses];

export type CreateRoleApiV1AuthRolesPostData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/roles/';
};

export type CreateRoleApiV1AuthRolesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoleApiV1AuthRolesPostError = CreateRoleApiV1AuthRolesPostErrors[keyof CreateRoleApiV1AuthRolesPostErrors];

export type CreateRoleApiV1AuthRolesPostResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type CreateRoleApiV1AuthRolesPostResponse = CreateRoleApiV1AuthRolesPostResponses[keyof CreateRoleApiV1AuthRolesPostResponses];

export type ReadRoleApiV1AuthRolesRoleIdGetData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/auth/roles/{role_id}';
};

export type ReadRoleApiV1AuthRolesRoleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRoleApiV1AuthRolesRoleIdGetError = ReadRoleApiV1AuthRolesRoleIdGetErrors[keyof ReadRoleApiV1AuthRolesRoleIdGetErrors];

export type ReadRoleApiV1AuthRolesRoleIdGetResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type ReadRoleApiV1AuthRolesRoleIdGetResponse = ReadRoleApiV1AuthRolesRoleIdGetResponses[keyof ReadRoleApiV1AuthRolesRoleIdGetResponses];

export type ReadPermissionsApiV1AuthPermissionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/auth/permissions/';
};

export type ReadPermissionsApiV1AuthPermissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPermissionsApiV1AuthPermissionsGetError = ReadPermissionsApiV1AuthPermissionsGetErrors[keyof ReadPermissionsApiV1AuthPermissionsGetErrors];

export type ReadPermissionsApiV1AuthPermissionsGetResponses = {
    /**
     * Successful Response
     */
    200: PermissionsPublic;
};

export type ReadPermissionsApiV1AuthPermissionsGetResponse = ReadPermissionsApiV1AuthPermissionsGetResponses[keyof ReadPermissionsApiV1AuthPermissionsGetResponses];

export type CreatePermissionApiV1AuthPermissionsPostData = {
    body: PermissionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/permissions/';
};

export type CreatePermissionApiV1AuthPermissionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePermissionApiV1AuthPermissionsPostError = CreatePermissionApiV1AuthPermissionsPostErrors[keyof CreatePermissionApiV1AuthPermissionsPostErrors];

export type CreatePermissionApiV1AuthPermissionsPostResponses = {
    /**
     * Successful Response
     */
    200: PermissionPublic;
};

export type CreatePermissionApiV1AuthPermissionsPostResponse = CreatePermissionApiV1AuthPermissionsPostResponses[keyof CreatePermissionApiV1AuthPermissionsPostResponses];

export type ReadPermissionApiV1AuthPermissionsPermissionIdGetData = {
    body?: never;
    path: {
        /**
         * Permission Id
         */
        permission_id: string;
    };
    query?: never;
    url: '/api/v1/auth/permissions/{permission_id}';
};

export type ReadPermissionApiV1AuthPermissionsPermissionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPermissionApiV1AuthPermissionsPermissionIdGetError = ReadPermissionApiV1AuthPermissionsPermissionIdGetErrors[keyof ReadPermissionApiV1AuthPermissionsPermissionIdGetErrors];

export type ReadPermissionApiV1AuthPermissionsPermissionIdGetResponses = {
    /**
     * Successful Response
     */
    200: PermissionPublic;
};

export type ReadPermissionApiV1AuthPermissionsPermissionIdGetResponse = ReadPermissionApiV1AuthPermissionsPermissionIdGetResponses[keyof ReadPermissionApiV1AuthPermissionsPermissionIdGetResponses];

export type ReadItemsApiV1ItemsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ReadItemsApiV1ItemsGetErrors = {
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemsApiV1ItemsGetError = ReadItemsApiV1ItemsGetErrors[keyof ReadItemsApiV1ItemsGetErrors];

export type ReadItemsApiV1ItemsGetResponses = {
    /**
     * List of items retrieved successfully
     */
    200: ItemsPublic;
};

export type ReadItemsApiV1ItemsGetResponse = ReadItemsApiV1ItemsGetResponses[keyof ReadItemsApiV1ItemsGetResponses];

export type CreateItemApiV1ItemsPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type CreateItemApiV1ItemsPostErrors = {
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemApiV1ItemsPostError = CreateItemApiV1ItemsPostErrors[keyof CreateItemApiV1ItemsPostErrors];

export type CreateItemApiV1ItemsPostResponses = {
    /**
     * Item created successfully
     */
    201: Item;
};

export type CreateItemApiV1ItemsPostResponse = CreateItemApiV1ItemsPostResponses[keyof CreateItemApiV1ItemsPostResponses];

export type DeleteItemApiV1ItemsIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type DeleteItemApiV1ItemsIdDeleteErrors = {
    /**
     * Not enough permissions to delete this item
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Item not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemApiV1ItemsIdDeleteError = DeleteItemApiV1ItemsIdDeleteErrors[keyof DeleteItemApiV1ItemsIdDeleteErrors];

export type DeleteItemApiV1ItemsIdDeleteResponses = {
    /**
     * Item deleted successfully
     */
    200: Message;
};

export type DeleteItemApiV1ItemsIdDeleteResponse = DeleteItemApiV1ItemsIdDeleteResponses[keyof DeleteItemApiV1ItemsIdDeleteResponses];

export type ReadItemApiV1ItemsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ReadItemApiV1ItemsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemApiV1ItemsIdGetError = ReadItemApiV1ItemsIdGetErrors[keyof ReadItemApiV1ItemsIdGetErrors];

export type ReadItemApiV1ItemsIdGetResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type ReadItemApiV1ItemsIdGetResponse = ReadItemApiV1ItemsIdGetResponses[keyof ReadItemApiV1ItemsIdGetResponses];

export type UpdateItemApiV1ItemsIdPutData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type UpdateItemApiV1ItemsIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemApiV1ItemsIdPutError = UpdateItemApiV1ItemsIdPutErrors[keyof UpdateItemApiV1ItemsIdPutErrors];

export type UpdateItemApiV1ItemsIdPutResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type UpdateItemApiV1ItemsIdPutResponse = UpdateItemApiV1ItemsIdPutResponses[keyof UpdateItemApiV1ItemsIdPutResponses];

export type GetItemImagesApiV1ItemsItemIdImagesGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/images';
};

export type GetItemImagesApiV1ItemsItemIdImagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemImagesApiV1ItemsItemIdImagesGetError = GetItemImagesApiV1ItemsItemIdImagesGetErrors[keyof GetItemImagesApiV1ItemsItemIdImagesGetErrors];

export type GetItemImagesApiV1ItemsItemIdImagesGetResponses = {
    /**
     * Successful Response
     */
    200: ItemImagesPublic;
};

export type GetItemImagesApiV1ItemsItemIdImagesGetResponse = GetItemImagesApiV1ItemsItemIdImagesGetResponses[keyof GetItemImagesApiV1ItemsItemIdImagesGetResponses];

export type CreateItemImageApiV1ItemsItemIdImagesPostData = {
    body: ItemImageCreate;
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/v1/items/{item_id}/images';
};

export type CreateItemImageApiV1ItemsItemIdImagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemImageApiV1ItemsItemIdImagesPostError = CreateItemImageApiV1ItemsItemIdImagesPostErrors[keyof CreateItemImageApiV1ItemsItemIdImagesPostErrors];

export type CreateItemImageApiV1ItemsItemIdImagesPostResponses = {
    /**
     * Successful Response
     */
    200: ItemImagePublic;
};

export type CreateItemImageApiV1ItemsItemIdImagesPostResponse = CreateItemImageApiV1ItemsItemIdImagesPostResponses[keyof CreateItemImageApiV1ItemsItemIdImagesPostResponses];

export type TestEmailApiV1UtilsTestEmailPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type TestEmailApiV1UtilsTestEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestEmailApiV1UtilsTestEmailPostError = TestEmailApiV1UtilsTestEmailPostErrors[keyof TestEmailApiV1UtilsTestEmailPostErrors];

export type TestEmailApiV1UtilsTestEmailPostResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type TestEmailApiV1UtilsTestEmailPostResponse = TestEmailApiV1UtilsTestEmailPostResponses[keyof TestEmailApiV1UtilsTestEmailPostResponses];

export type HealthCheckApiV1UtilsHealthCheckGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type HealthCheckApiV1UtilsHealthCheckGetResponses = {
    /**
     * Response Health Check Api V1 Utils Health Check  Get
     *
     * Successful Response
     */
    200: boolean;
};

export type HealthCheckApiV1UtilsHealthCheckGetResponse = HealthCheckApiV1UtilsHealthCheckGetResponses[keyof HealthCheckApiV1UtilsHealthCheckGetResponses];
