/**
 * Barrels Events domain types.
 *
 * These describe the shape of the product, independent of where the data comes
 * from. Screens are built against these types so that replacing the fixture
 * data source with a database is an implementation change, not a rewrite.
 *
 * See `docs/products/barrels-events-v1-definition.md`.
 */

export type CurrencyCode = "XCD" | "USD";

/**
 * Money is always held in minor units (cents) as an integer. Never use a
 * floating-point number for an amount — format at the edge, calculate in minor
 * units.
 */
export interface Money {
  readonly amountMinor: number;
  readonly currency: CurrencyCode;
}

/** Publishing is deliberate: an event is not sellable until it leaves draft. */
export type EventStatus = "draft" | "on-sale" | "closed";

export interface EventRecord {
  /** One capacity pool. Every sales channel draws from it. */
  readonly capacity: number;
  readonly id: string;
  readonly isDemo: boolean;
  readonly name: string;
  /** ISO 8601 with offset. */
  readonly startsAt: string;
  readonly status: EventStatus;
  readonly venue: string;
}

export interface TicketType {
  /** Share of the event capacity this type may draw. */
  readonly allocation: number;
  readonly eventId: string;
  readonly id: string;
  readonly name: string;
  readonly price: Money;
}

/**
 * Every sale lands in one ledger regardless of where it happened. Organisers
 * currently reconcile these channels by hand.
 */
export type SalesChannelId = "online" | "outlet" | "complimentary" | "door";

export type ReconciliationState = "reconciled" | "needs-count" | "recorded";

export interface ChannelSales {
  readonly channel: SalesChannelId;
  readonly gross: Money;
  readonly label: string;
  readonly orders: number;
  readonly reconciliation: ReconciliationState;
  readonly tickets: number;
}

export type OrderStatus = "pending" | "paid" | "refunded" | "cancelled";

export interface Order {
  readonly channel: SalesChannelId;
  readonly eventId: string;
  readonly id: string;
  readonly placedAt: string;
  /** Organiser-facing reference, shown on the door manifest. */
  readonly reference: string;
  readonly status: OrderStatus;
  readonly total: Money;
}

export type TicketState = "issued" | "void" | "refunded";

export interface Ticket {
  /** The code presented at the door. */
  readonly code: string;
  readonly id: string;
  readonly orderId: string;
  readonly state: TicketState;
  readonly ticketTypeId: string;
}

export type ScanResult = "admitted" | "duplicate" | "not-found" | "void";

/**
 * Admission is an append-only log. A ticket's admitted state is a projection
 * over these entries; the server is authoritative on ordering.
 *
 * `idempotencyKey` and `clientRecordedAt` are generated by the scanning device
 * so that the same physical scan is never counted twice, and so that buffering
 * scans for later replay stays additive.
 */
export interface ScanEvent {
  /** When the device recorded the scan. */
  readonly clientRecordedAt: string;
  readonly deviceId: string;
  readonly idempotencyKey: string;
  readonly result: ScanResult;
  /** When the server accepted it. Absent until accepted. */
  readonly serverRecordedAt: string | null;
  readonly ticketId: string;
}

export interface SettlementDeduction {
  readonly amount: Money;
  readonly label: string;
}

export interface SettlementPreview {
  readonly deductions: readonly SettlementDeduction[];
  readonly gross: Money;
  /** Derived: gross less every deduction. */
  readonly net: Money;
}

export type ReadinessState = "complete" | "attention";

export interface ReadinessCheck {
  readonly detail: string;
  readonly id: string;
  readonly state: ReadinessState;
  readonly title: string;
}

export type ActionPriority = "required" | "attention" | "scheduled";

export interface NextAction {
  readonly detail: string;
  readonly id: string;
  readonly priority: ActionPriority;
  readonly statusLabel: string;
  readonly title: string;
}

export interface OperationalRecord {
  readonly lastPaymentChannel: string;
  readonly lastPaymentLabel: string;
  readonly openExceptions: number;
  readonly openExceptionsDetail: string;
}

export interface SalesTotals {
  readonly gross: Money;
  readonly orders: number;
  readonly tickets: number;
}

/** Everything the organiser overview needs, assembled by the data layer. */
export interface EventDashboard {
  readonly actions: readonly NextAction[];
  readonly channels: readonly ChannelSales[];
  readonly countdownLabel: string;
  readonly event: EventRecord;
  readonly operational: OperationalRecord;
  readonly readinessChecks: readonly ReadinessCheck[];
  readonly readinessPercent: number;
  readonly salesTrendLabel: string;
  readonly settlement: SettlementPreview;
  readonly totals: SalesTotals;
}
