/**
 * Barrels Events domain types.
 *
 * These describe the shape of the product, independent of where the data comes
 * from. Screens are built against these types so that replacing the fixture
 * data source with a database is an implementation change, not a rewrite.
 *
 * See `docs/products/barrels-events-v1-definition.md`.
 */

export type CurrencyCode = "XCD" | "USD";

/**
 * Money is always held in minor units (cents) as an integer. Never use a
 * floating-point number for an amount — format at the edge, calculate in minor
 * units.
 */
export interface Money {
  readonly amountMinor: number;
  readonly currency: CurrencyCode;
}

/** Publishing is deliberate: an event is not sellable until it leaves draft. */
export type EventStatus = "draft" | "on-sale" | "closed";

export interface EventRecord {
  /** One capacity pool. Every sales channel draws from it. */
  readonly capacity: number;
  readonly id: string;
  readonly isDemo: boolean;
  readonly name: string;
  /** ISO 8601 with offset. */
  readonly startsAt: string;
  readonly status: EventStatus;
  readonly venue: string;
}

export interface TicketType {
  /** Share of the event capacity this type may draw. */
  readonly allocation: number;
  readonly eventId: string;
  readonly id: string;
  readonly name: string;
  readonly price: Money;
}

/**
 * Every sale lands in one ledger regardless of where it happened. Organisers
 * currently reconcile these channels by hand.
 */
export type SalesChannelId = "online" | "outlet" | "complimentary" | "door";

export type ReconciliationState = "reconciled" | "needs-count" | "recorded";

export interface ChannelSales {
  readonly channel: SalesChannelId;
  readonly gross: Money;
  readonly label: string;
  readonly orders: number;
  readonly reconciliation: ReconciliationState;
  readonly tickets: number;
}

export type OrderStatus = "pending" | "paid" | "refunded" | "cancelled";

export interface Order {
  readonly channel: SalesChannelId;
  readonly eventId: string;
  readonly id: string;
  readonly placedAt: string;
  /** Organiser-facing reference, shown on the door manifest. */
  readonly reference: string;
  readonly status: OrderStatus;
  readonly total: Money;
}

export type TicketState = "issued" | "void" | "refunded";

export interface Ticket {
  /** The code presented at the door. */
  readonly code: string;
  readonly id: string;
  readonly orderId: string;
  readonly state: TicketState;
  readonly ticketTypeId: string;
}

export type ScanResult = "admitted" | "duplicate" | "not-found" | "void";

/**
 * Admission is an append-only log. A ticket's admitted state is a projection
 * over these entries; the server is authoritative on ordering.
 *
 * `idempotencyKey` and `clientRecordedAt` are generated by the scanning device
 * so that the same physical scan is never counted twice, and so that buffering
 * scans for later replay stays additive.
 */
export interface ScanEvent {
  /** When the device recorded the scan. */
  readonly clientRecordedAt: string;
  readonly deviceId: string;
  readonly idempotencyKey: string;
  readonly result: ScanResult;
  /** When the server accepted it. Absent until accepted. */
  readonly serverRecordedAt: string | null;
  readonly ticketId: string;
}

export interface SettlementDeduction {
  readonly amount: Money;
  readonly label: string;
}

export interface SettlementPreview {
  readonly deductions: readonly SettlementDeduction[];
  readonly gross: Money;
  /** Derived: gross less every deduction. */
  readonly net: Money;
}

export type ReadinessState = "complete" | "attention";

export interface ReadinessCheck {
  readonly detail: string;
  readonly id: string;
  readonly state: ReadinessState;
  readonly title: string;
}

export type ActionPriority = "required" | "attention" | "scheduled";

export interface NextAction {
  readonly detail: string;
  readonly id: string;
  readonly priority: ActionPriority;
  readonly statusLabel: string;
  readonly title: string;
}

export interface OperationalRecord {
  readonly lastPaymentChannel: string;
  readonly lastPaymentLabel: string;
  readonly openExceptions: number;
  readonly openExceptionsDetail: string;
}

export interface SalesTotals {
  readonly gross: Money;
  readonly orders: number;
  readonly tickets: number;
}

/** Everything the organiser overview needs, assembled by the data layer. */
export interface EventDashboard {
  readonly actions: readonly NextAction[];
  readonly channels: readonly ChannelSales[];
  readonly countdownLabel: string;
  readonly event: EventRecord;
  readonly operational: OperationalRecord;
  readonly readinessChecks: readonly ReadinessCheck[];
  readonly readinessPercent: number;
  readonly salesTrendLabel: string;
  readonly settlement: SettlementPreview;
  readonly totals: SalesTotals;
}

/*
 * Public discovery and community.
 *
 * The attendee-facing side: every event in Grenada, the groups that run
 * recurring meetups, and the people who go. Shaped for a future FastAPI
 * backend; fixtures stand in until then.
 */

export type EventCategory =
  | "fete"
  | "music"
  | "food"
  | "sport"
  | "business"
  | "tech"
  | "culture"
  | "faith"
  | "family"
  | "wellness";

export type Parish =
  | "st-george"
  | "st-andrew"
  | "st-david"
  | "st-patrick"
  | "st-mark"
  | "st-john"
  | "carriacou";

/** Free walk-in, free with RSVP, or a paid ticket. */
export type Admission = "free" | "rsvp" | "ticketed";

export interface Organiser {
  readonly bio: string;
  readonly followerCount: number;
  readonly id: string;
  readonly name: string;
  readonly slug: string;
  /** Verification is earned, never bought or transferred. */
  readonly verified: boolean;
}

export interface PublicEvent {
  readonly admission: Admission;
  readonly category: EventCategory;
  readonly description: string;
  /** ISO 8601 with offset. */
  readonly endsAt: string;
  readonly featured: boolean;
  /** Profile ids of people going. */
  readonly goingIds: readonly string[];
  readonly groupId: string | null;
  readonly id: string;
  readonly isDemo: boolean;
  readonly organiserId: string;
  readonly parish: Parish;
  /** Lowest ticket price. Null unless admission is "ticketed". */
  readonly priceFrom: Money | null;
  /** Human label for a series, e.g. "Every Tuesday". */
  readonly recurrence: string | null;
  readonly slug: string;
  /** ISO 8601 with offset. */
  readonly startsAt: string;
  readonly summary: string;
  readonly title: string;
  readonly venue: string;
}

export interface GroupAnnouncement {
  readonly authorId: string;
  readonly body: string;
  readonly id: string;
  readonly postedAt: string;
}

export interface Group {
  readonly about: string;
  readonly announcements: readonly GroupAnnouncement[];
  readonly category: EventCategory;
  readonly hostIds: readonly string[];
  readonly id: string;
  /** "approval" groups review join requests before membership. */
  readonly joinPolicy: "open" | "approval";
  readonly name: string;
  readonly parish: Parish;
  readonly slug: string;
  readonly tagline: string;
}

/** What someone is open to — Brella-style intent, shown on their profile. */
export type Intent =
  | "making-friends"
  | "hiring"
  | "looking-for-work"
  | "collaborating"
  | "mentoring";

export interface Profile {
  readonly attendedEventIds: readonly string[];
  readonly bio: string;
  readonly groupIds: readonly string[];
  readonly handle: string;
  readonly headline: string;
  readonly id: string;
  readonly intents: readonly Intent[];
  readonly interests: readonly EventCategory[];
  readonly name: string;
  readonly parish: Parish;
  /** "connections" hides details from people outside the member's network. */
  readonly visibility: "public" | "connections";
}

export interface Connection {
  readonly id: string;
  readonly profileIds: readonly [string, string];
  readonly requestedBy: string;
  readonly status: "pending" | "accepted";
}

export interface Message {
  readonly authorId: string;
  readonly body: string;
  readonly id: string;
  readonly sentAt: string;
}

export interface MessageThread {
  readonly groupId: string | null;
  readonly id: string;
  readonly kind: "direct" | "group";
  readonly messages: readonly Message[];
  readonly participantIds: readonly string[];
}

export interface EventFilters {
  readonly category?: EventCategory;
  readonly parish?: Parish;
  readonly price?: "free" | "paid";
  readonly query?: string;
  readonly when?: "tonight" | "weekend" | "week" | "month";
}
